arqade.Posts <- data.table(read.csv("arqade.stackexchange/Posts.xml.csv"))
arqade.Users <- data.table(read.csv("arqade.stackexchange/Users.xml.csv"))
chess.Posts <- data.table(read.csv("chess.stackexchange/Posts.xml.csv"))
chess.Users <- data.table(read.csv("chess.stackexchange/Users.xml.csv"))
boarding.Posts <- data.table(read.csv("boardinggames.stackexchange/Posts.xml.csv"))
boarding.Users <- data.table(read.csv("boardinggames.stackexchange/Users.xml.csv"))
